/**
 * Generated by AgentReady (https://github.com/vb-nattamai/agent-ready)
 * Tool Template: TypeScript
 *
 * This is a scaffold for creating MCP-compatible tools in TypeScript.
 * Replace the placeholder implementation with your actual tool logic.
 */

// --- Types ---

interface ToolResult<T = unknown> {
  success: boolean;
  data: T | null;
  error: string | null;
}

interface {{TOOL_NAME_PASCAL}}Input {
  {{PARAM_1_NAME}}: {{PARAM_1_TYPE}};
  {{PARAM_2_NAME}}?: {{PARAM_2_TYPE}};
}

interface {{TOOL_NAME_PASCAL}}Output {
  // TODO: Define your output shape
  result: string;
}

// --- Tool Implementation ---

export async function tool{{TOOL_NAME_PASCAL}}(
  input: {{TOOL_NAME_PASCAL}}Input
): Promise<ToolResult<{{TOOL_NAME_PASCAL}}Output>> {
  // --- Input Validation ---
  if (!input.{{PARAM_1_NAME}}) {
    return {
      success: false,
      data: null,
      error: `{{PARAM_1_NAME}} is required and cannot be empty`,
    };
  }

  try {
    // --- Tool Logic ---
    // TODO: Replace with actual implementation
    const result = await executeToolLogic(
      input.{{PARAM_1_NAME}},
      input.{{PARAM_2_NAME}} ?? {{PARAM_2_DEFAULT}}
    );

    return {
      success: true,
      data: result,
      error: null,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      data: null,
      error: message,
    };
  }
}

async function executeToolLogic(
  {{PARAM_1_NAME}}: {{PARAM_1_TYPE}},
  {{PARAM_2_NAME}}: {{PARAM_2_TYPE}}
): Promise<{{TOOL_NAME_PASCAL}}Output> {
  // TODO: Implement actual logic
  throw new Error("Replace this with your tool's implementation");
}

// --- Tool Metadata (MCP-compatible) ---

export const TOOL_METADATA = {
  name: "{{TOOL_NAME}}",
  description: "{{TOOL_DESCRIPTION}}",
  inputSchema: {
    type: "object" as const,
    properties: {
      {{PARAM_1_NAME}}: {
        type: "{{PARAM_1_JSON_TYPE}}",
        description: "{{PARAM_1_DESCRIPTION}}",
      },
      {{PARAM_2_NAME}}: {
        type: "{{PARAM_2_JSON_TYPE}}",
        description: "{{PARAM_2_DESCRIPTION}}",
        default: {{PARAM_2_DEFAULT}},
      },
    },
    required: ["{{PARAM_1_NAME}}"],
  },
} as const;

// --- Quick Test ---

if (require.main === module) {
  tool{{TOOL_NAME_PASCAL}}({
    {{PARAM_1_NAME}}: "test_value",
  }).then((result) => {
    console.log(JSON.stringify(result, null, 2));
  });
}
