/*
 * Generated by AgentReady (https://github.com/vb-nattamai/agent-ready)
 * Tool Template: Go
 *
 * This is a scaffold for creating MCP-compatible tools in Go.
 * Replace the placeholder implementation with your actual tool logic.
 */

package tools

import (
	"encoding/json"
	"fmt"
)

// ToolResult represents the standardized result of a tool execution.
type ToolResult struct {
	Success bool        `json:"success"`
	Data    interface{} `json:"data"`
	Error   *string     `json:"error"`
}

// {{TOOL_NAME_PASCAL}}Input defines the input parameters for the tool.
type {{TOOL_NAME_PASCAL}}Input struct {
	{{PARAM_1_NAME_PASCAL}} {{PARAM_1_TYPE}} `json:"{{PARAM_1_NAME}}" validate:"required"`
	{{PARAM_2_NAME_PASCAL}} {{PARAM_2_TYPE}} `json:"{{PARAM_2_NAME}},omitempty"`
}

// {{TOOL_NAME_PASCAL}}Output defines the output data from the tool.
type {{TOOL_NAME_PASCAL}}Output struct {
	// TODO: Define your output fields
	Result string `json:"result"`
}

// Tool{{TOOL_NAME_PASCAL}} executes the {{TOOL_NAME}} tool.
//
// {{TOOL_DESCRIPTION}}
func Tool{{TOOL_NAME_PASCAL}}(input {{TOOL_NAME_PASCAL}}Input) ToolResult {
	// --- Input Validation ---
	if input.{{PARAM_1_NAME_PASCAL}} == "" {
		errMsg := "{{PARAM_1_NAME}} is required and cannot be empty"
		return ToolResult{
			Success: false,
			Data:    nil,
			Error:   &errMsg,
		}
	}

	// --- Tool Logic ---
	result, err := executeToolLogic(input.{{PARAM_1_NAME_PASCAL}}, input.{{PARAM_2_NAME_PASCAL}})
	if err != nil {
		errMsg := err.Error()
		return ToolResult{
			Success: false,
			Data:    nil,
			Error:   &errMsg,
		}
	}

	return ToolResult{
		Success: true,
		Data:    result,
		Error:   nil,
	}
}

// executeToolLogic contains the internal implementation of the tool.
// Separated for testability.
func executeToolLogic(
	{{PARAM_1_NAME}} {{PARAM_1_TYPE}},
	{{PARAM_2_NAME}} {{PARAM_2_TYPE}},
) (*{{TOOL_NAME_PASCAL}}Output, error) {
	// TODO: Implement actual logic
	return nil, fmt.Errorf("replace this with your tool's implementation")
}

// ToolMetadata returns MCP-compatible metadata for the tool.
func ToolMetadata() map[string]interface{} {
	return map[string]interface{}{
		"name":        "{{TOOL_NAME}}",
		"description": "{{TOOL_DESCRIPTION}}",
		"inputSchema": map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"{{PARAM_1_NAME}}": map[string]interface{}{
					"type":        "{{PARAM_1_JSON_TYPE}}",
					"description": "{{PARAM_1_DESCRIPTION}}",
				},
				"{{PARAM_2_NAME}}": map[string]interface{}{
					"type":        "{{PARAM_2_JSON_TYPE}}",
					"description": "{{PARAM_2_DESCRIPTION}}",
					"default":     "{{PARAM_2_DEFAULT}}",
				},
			},
			"required": []string{"{{PARAM_1_NAME}}"},
		},
	}
}

func main() {
	input := {{TOOL_NAME_PASCAL}}Input{
		{{PARAM_1_NAME_PASCAL}}: "test_value",
	}
	result := Tool{{TOOL_NAME_PASCAL}}(input)

	output, _ := json.MarshalIndent(result, "", "  ")
	fmt.Println(string(output))
}
