"""
Generated by AgentReady (https://github.com/vb-nattamai/agent-ready)
Tool Template: Python

This is a scaffold for creating MCP-compatible tools in Python.
Replace the placeholder implementation with your actual tool logic.
"""

from typing import Any


def tool_{{TOOL_NAME}}(
    {{PARAM_1_NAME}}: {{PARAM_1_TYPE}},
    {{PARAM_2_NAME}}: {{PARAM_2_TYPE}} = {{PARAM_2_DEFAULT}},
) -> dict[str, Any]:
    """{{TOOL_DESCRIPTION}}

    Args:
        {{PARAM_1_NAME}}: {{PARAM_1_DESCRIPTION}}
        {{PARAM_2_NAME}}: {{PARAM_2_DESCRIPTION}}

    Returns:
        A dictionary containing the tool's result with keys:
        - success (bool): Whether the operation succeeded
        - data (Any): The result data
        - error (str | None): Error message if failed

    Raises:
        ValueError: If required parameters are invalid
        RuntimeError: If the tool operation fails
    """
    # --- Input Validation ---
    if not {{PARAM_1_NAME}}:
        return {
            "success": False,
            "data": None,
            "error": f"{{PARAM_1_NAME}} is required and cannot be empty",
        }

    try:
        # --- Tool Logic ---
        # TODO: Replace with actual implementation
        result = _execute_tool_logic({{PARAM_1_NAME}}, {{PARAM_2_NAME}})

        return {
            "success": True,
            "data": result,
            "error": None,
        }

    except Exception as e:
        return {
            "success": False,
            "data": None,
            "error": str(e),
        }


def _execute_tool_logic(
    {{PARAM_1_NAME}}: {{PARAM_1_TYPE}},
    {{PARAM_2_NAME}}: {{PARAM_2_TYPE}},
) -> Any:
    """Internal implementation of the tool logic.

    Separated for testability.
    """
    # TODO: Implement actual logic
    raise NotImplementedError("Replace this with your tool's implementation")


# --- Tool Metadata (MCP-compatible) ---
TOOL_METADATA = {
    "name": "{{TOOL_NAME}}",
    "description": "{{TOOL_DESCRIPTION}}",
    "inputSchema": {
        "type": "object",
        "properties": {
            "{{PARAM_1_NAME}}": {
                "type": "{{PARAM_1_JSON_TYPE}}",
                "description": "{{PARAM_1_DESCRIPTION}}",
            },
            "{{PARAM_2_NAME}}": {
                "type": "{{PARAM_2_JSON_TYPE}}",
                "description": "{{PARAM_2_DESCRIPTION}}",
                "default": {{PARAM_2_DEFAULT}},
            },
        },
        "required": ["{{PARAM_1_NAME}}"],
    },
}


if __name__ == "__main__":
    # Quick test
    import json

    result = tool_{{TOOL_NAME}}(
        {{PARAM_1_NAME}}="test_value",
    )
    print(json.dumps(result, indent=2))
