/*
 * Generated by AgentReady (https://github.com/vb-nattamai/agent-ready)
 * Tool Template: Java
 *
 * This is a scaffold for creating MCP-compatible tools in Java.
 * Replace the placeholder implementation with your actual tool logic.
 */

package {{PACKAGE_NAME}}.tools;

import java.util.HashMap;
import java.util.Map;

/**
 * {{TOOL_DESCRIPTION}}
 *
 * <p>MCP-compatible tool implementation with input validation,
 * error handling, and structured result output.</p>
 */
public class {{TOOL_NAME_PASCAL}}Tool {

    /**
     * Tool result container.
     */
    public static class ToolResult {
        private final boolean success;
        private final Object data;
        private final String error;

        private ToolResult(boolean success, Object data, String error) {
            this.success = success;
            this.data = data;
            this.error = error;
        }

        public static ToolResult success(Object data) {
            return new ToolResult(true, data, null);
        }

        public static ToolResult failure(String error) {
            return new ToolResult(false, null, error);
        }

        public boolean isSuccess() { return success; }
        public Object getData() { return data; }
        public String getError() { return error; }

        @Override
        public String toString() {
            return String.format("{\"success\": %s, \"data\": %s, \"error\": %s}",
                success,
                data != null ? "\"" + data + "\"" : "null",
                error != null ? "\"" + error + "\"" : "null");
        }
    }

    /**
     * Execute the tool with the given parameters.
     *
     * @param {{PARAM_1_NAME}} {{PARAM_1_DESCRIPTION}}
     * @param {{PARAM_2_NAME}} {{PARAM_2_DESCRIPTION}}
     * @return ToolResult containing success status, data, and optional error
     */
    public ToolResult execute({{PARAM_1_TYPE}} {{PARAM_1_NAME}}, {{PARAM_2_TYPE}} {{PARAM_2_NAME}}) {
        // --- Input Validation ---
        if ({{PARAM_1_NAME}} == null || {{PARAM_1_NAME}}.isEmpty()) {
            return ToolResult.failure("{{PARAM_1_NAME}} is required and cannot be empty");
        }

        try {
            // --- Tool Logic ---
            // TODO: Replace with actual implementation
            Object result = executeToolLogic({{PARAM_1_NAME}}, {{PARAM_2_NAME}});

            return ToolResult.success(result);

        } catch (Exception e) {
            return ToolResult.failure(e.getMessage());
        }
    }

    /**
     * Internal implementation of the tool logic.
     * Separated for testability.
     */
    private Object executeToolLogic({{PARAM_1_TYPE}} {{PARAM_1_NAME}}, {{PARAM_2_TYPE}} {{PARAM_2_NAME}}) {
        // TODO: Implement actual logic
        throw new UnsupportedOperationException("Replace this with your tool's implementation");
    }

    /**
     * Returns MCP-compatible tool metadata.
     */
    public static Map<String, Object> getToolMetadata() {
        Map<String, Object> metadata = new HashMap<>();
        metadata.put("name", "{{TOOL_NAME}}");
        metadata.put("description", "{{TOOL_DESCRIPTION}}");

        Map<String, Object> inputSchema = new HashMap<>();
        inputSchema.put("type", "object");

        Map<String, Object> properties = new HashMap<>();

        Map<String, Object> param1 = new HashMap<>();
        param1.put("type", "{{PARAM_1_JSON_TYPE}}");
        param1.put("description", "{{PARAM_1_DESCRIPTION}}");
        properties.put("{{PARAM_1_NAME}}", param1);

        Map<String, Object> param2 = new HashMap<>();
        param2.put("type", "{{PARAM_2_JSON_TYPE}}");
        param2.put("description", "{{PARAM_2_DESCRIPTION}}");
        param2.put("default", "{{PARAM_2_DEFAULT}}");
        properties.put("{{PARAM_2_NAME}}", param2);

        inputSchema.put("properties", properties);
        inputSchema.put("required", new String[]{"{{PARAM_1_NAME}}"});

        metadata.put("inputSchema", inputSchema);

        return metadata;
    }

    // --- Quick Test ---
    public static void main(String[] args) {
        {{TOOL_NAME_PASCAL}}Tool tool = new {{TOOL_NAME_PASCAL}}Tool();
        ToolResult result = tool.execute("test_value", {{PARAM_2_DEFAULT}});
        System.out.println(result);
    }
}
